# coding: utf-8

"""
    PetStoreAPI

    A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="PetStoreAPI",
    description="A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
